name: Build Native Binaries

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-darwin:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build binary for ${{ matrix.arch }}
        run: |
          pyinstaller --onefile app.py  --name fingertrack\
            --add-binary "$(python -c 'import cv2; import os; print(os.path.join(os.path.dirname(cv2.__file__), "cv2.abi3.so"))')":cv2 \
            --add-data "$(python -c 'import mediapipe as mp, os; print(os.path.join(os.path.dirname(mp.__file__), "modules"))')":mediapipe/modules

          if [ "${{ matrix.arch }}" = "x86_64" ]; then
            mv dist/fingertrack dist/fingertrack-darwin-amd64
          else
            mv dist/fingertrack dist/fingertrack-darwin-arm64
          fi

      - name: Upload binaries as artifact
        uses: actions/upload-artifact@v4
        with:
          name: fingertrack-darwin-${{ matrix.arch == 'x86_64' && 'amd64' || matrix.arch }}
          path: dist/*

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Windows binary
        shell: bash
        run: |
          pyinstaller --onefile app.py  --name fingertrack\
            --add-binary "$(python -c 'import cv2; import os; print(os.path.join(os.path.dirname(cv2.__file__), "cv2.pyd"))')":cv2 \
            --add-data "$(python -c 'import mediapipe as mp, os; print(os.path.join(os.path.dirname(mp.__file__), "modules"))')":mediapipe/modules
          mv dist/fingertrack.exe dist/fingertrack-windows-amd64.exe

      - name: Upload Windows binaries
        uses: actions/upload-artifact@v4
        with:
          name: fingertrack-windows-amd64
          path: dist/*

  release:
    needs: [build-darwin, build-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Download darwin amd64 artifacts
        uses: actions/download-artifact@v4
        with:
          name: fingertrack-darwin-amd64
          path: dist/darwin-amd64

      - name: Download arm64 artifacts
        uses: actions/download-artifact@v4
        with:
          name: fingertrack-darwin-arm64
          path: dist/darwin-arm64

      - name: Download Windows amd64
        uses: actions/download-artifact@v4
        with:
          name: fingertrack-windows-amd64
          path: dist/windows-amd64

      - name: Create GitHub Release and Upload Binaries
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: FingerTrack ${{ github.ref_name }}
          files: |
            dist/darwin-amd64/fingertrack-darwin-amd64
            dist/darwin-arm64/fingertrack-darwin-arm64
            dist/windows-amd64/fingertrack-windows-amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
